### ISSUE TITLE
You're doing amazing work here

### ISSUE THREAD

**Issue by jquast** [dorawyy/git-merge-conflicts-test#82]
I presume this is for school?

Very good documentation you've authored here.

Have a wonderful day

**Comment by dorawyy** [comment]
Hi Jeff,

Sorry for the late reply, I was working on another deadline. I am glad that you find the repository useful! Yes, it is for my personal use to test how git proceeds merge with different configs in different scenarios. Happy to discuss if you have any comments/suggestions, etc.

Best,
Yingying

**Comment by jquast** [comment]
I only suggest that if you are graduating soon and interested in software engineering in aviation, you would please let me know! jeff.quast@joby.aero

**Comment by jquast** [comment]
Just wanted to remind you that I think your writing is very good. I hope we can hear from you someday in the future :)
